<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Buat Event Baru_popupiframe</name>
   <tag></tag>
   <elementGuidId>e6f35491-5a16-4237-8602-74a6c00bbb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#popupiframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='popupiframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>35fa42d5-9665-4630-a8c6-87618352bba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupiframe</value>
      <webElementGuid>79e1682b-dcc5-45bb-b344-aa0d10912e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://192.168.29.74/master/event/create</value>
      <webElementGuid>1d7d77a3-d5bc-4725-9e3d-70fc595fcb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1504f13d-475d-44a9-ab10-75da6b02d7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>30a92fa3-41a5-4be2-ab5d-e0fc2f3ed6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>350px</value>
      <webElementGuid>71ebd654-24b5-4453-a5de-ade639981bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupiframe&quot;)</value>
      <webElementGuid>20c59d23-856b-463f-92a5-73dccdacd745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='popupiframe']</value>
      <webElementGuid>40061a24-d64f-4079-a646-848445fecef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalSetting']/div/div/div[2]/div/iframe</value>
      <webElementGuid>01a695e7-b892-4c7b-831e-915b25fa2431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Event Baru'])[1]/following::iframe[1]</value>
      <webElementGuid>372f8892-bed4-43f2-97b1-623b3a8d4940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Event'])[4]/following::iframe[2]</value>
      <webElementGuid>1f7796d4-2473-4d28-a2d0-17b940de7f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::iframe[1]</value>
      <webElementGuid>b3fb2057-ea86-489f-9e00-fcc0c06be799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::iframe[1]</value>
      <webElementGuid>a11196f6-e446-489b-956d-7d37b1307d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/iframe</value>
      <webElementGuid>8b9b8e5b-51f7-4e26-a3d3-5bd3551b3239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'popupiframe' and @src = 'http://192.168.29.74/master/event/create']</value>
      <webElementGuid>1bd8eed7-559c-4fd5-afe0-96835ec70183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
