<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout_main-iframe</name>
   <tag></tag>
   <elementGuidId>3e21fd9c-27a8-4294-8891-e85e292734c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='main-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>038342a0-05d8-4fb4-8a8c-25df0c39f759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-iframe</value>
      <webElementGuid>df713c13-90bb-46f4-9cd5-16de8c36ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/master/event_dealer/list</value>
      <webElementGuid>62043ffe-ccbd-4e96-a42f-15d778cec54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a6d951d-ce8d-49ed-90d1-d0a5b0bdcc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>75d68659-7146-4256-9377-ffc99b8d3336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1000px</value>
      <webElementGuid>2cde799f-c145-475c-8602-d5fe84fabcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-iframe&quot;)</value>
      <webElementGuid>fd9a729f-d5ae-4d3f-87f3-71ae68695dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='main-iframe']</value>
      <webElementGuid>e012acbc-ed5f-41c6-acef-2f3ea8eee96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div/iframe</value>
      <webElementGuid>e4960f71-5912-4454-ae37-33d9af4a446c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fdb40329-03a4-499b-aa50-abaaa672d0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'main-iframe' and @src = '/master/event_dealer/list']</value>
      <webElementGuid>2b363f4a-c8df-4d9a-93e4-0e87664c1860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
