<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Master Event_main-iframe (1)</name>
   <tag></tag>
   <elementGuidId>ca687302-58dd-462c-bb7f-15189cd12c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='main-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8de1b143-feb9-437c-90e6-605f63875f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-iframe</value>
      <webElementGuid>bc5dd008-47c3-48f6-abee-459987fa2fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/master/event/list</value>
      <webElementGuid>c618e10e-7a22-413a-9220-6760a0a622c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f8082ac-30ed-40de-abc6-2a6466eb9932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>59674f6a-3bf8-4c87-99d4-83d8899b5520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>750px;</value>
      <webElementGuid>babaa19b-da92-4098-8166-f4f245bb9049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-iframe&quot;)</value>
      <webElementGuid>f04377fb-948d-47bd-9d87-e8e8f49e3abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='main-iframe']</value>
      <webElementGuid>c1ba6980-c58a-48de-8adb-079af07ea10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div[2]/div/section/div/iframe</value>
      <webElementGuid>9797e7da-13fe-4dd5-b508-4ff8589212cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>48e59d0d-9e5c-4fa3-969b-e23112cd7e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'main-iframe' and @src = '/master/event/list']</value>
      <webElementGuid>e4b5953d-4dc4-41ef-8cc9-377959e6292a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
