<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Master Event_main-iframe</name>
   <tag></tag>
   <elementGuidId>e8df9b30-6e3f-4ed7-940b-3cd9925baf0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='main-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>acaea7da-81c9-4379-8ad9-3049c211215f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-iframe</value>
      <webElementGuid>a635f161-6fc1-4a90-8492-740dcef2f901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/master/event/list</value>
      <webElementGuid>ac7c0827-bae9-453a-86b7-29a1bc03d354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3caf9f4b-4a8b-47e4-8554-1ee54e126930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>0212b7ee-6fd3-47eb-8f22-52a34cad728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>750px;</value>
      <webElementGuid>0a2ede7b-73f3-4da2-a6b3-9f06f1449e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-iframe&quot;)</value>
      <webElementGuid>e0b5440e-aa08-4d08-bd51-a809cb9000d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='main-iframe']</value>
      <webElementGuid>dbff8efd-9782-46d1-84f2-7c982ecd5ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div[2]/div/section/div/iframe</value>
      <webElementGuid>a4939584-33ac-431a-aaaf-e28bf1f81cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9152d11e-7386-42f6-8499-3fb8d8b5b636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'main-iframe' and @src = '/master/event/list']</value>
      <webElementGuid>f73d627e-84cd-4d1e-ba20-e917152a4d11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
