<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KCU_form-control input-search-kanwil-kcu</name>
   <tag></tag>
   <elementGuidId>8a738829-cf7b-4f19-9b8e-7479739e9c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.input-search-kanwil-kcu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38e8d924-a89c-40fa-9cab-629381ad9fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8c5215e-7d9e-4751-8ab6-4697930f38a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-search-kanwil-kcu</value>
      <webElementGuid>9467ecc4-ab0a-4127-bdfa-6077d19a9518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEdit&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;parent-group&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;parent-group&quot;]/input[@class=&quot;form-control input-search-kanwil-kcu&quot;]</value>
      <webElementGuid>220dd946-2689-43e5-b826-dacc0f6eedd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>bbcd38f2-686c-4aeb-a8cd-03bc4fe4cd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEdit']/div[2]/div[2]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>130bd63f-d673-4c41-a6c2-ff22e391514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>74fc991d-ee94-460b-b173-91aabaeba75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>6039b0b4-971e-4344-8011-10e8efe5d7d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
