<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KCU_cbx</name>
   <tag></tag>
   <elementGuidId>2903698b-ae92-4e00-82e8-2b84002b3df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-kanwil-kcu > thead > tr > th.text-center > div.checkbox-wrapper > label > span.cbx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-kanwil-kcu']/thead/tr/th/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d58c2f90-0212-47e1-ac1b-27cd6381a579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbx</value>
      <webElementGuid>3130cd2f-0169-4f0f-b013-edb5a195c7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-kanwil-kcu&quot;)/thead[1]/tr[1]/th[@class=&quot;text-center&quot;]/div[@class=&quot;checkbox-wrapper&quot;]/label[1]/span[@class=&quot;cbx&quot;]</value>
      <webElementGuid>eb149cd7-1db7-4914-96f5-8011847affd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-kanwil-kcu']/thead/tr/th/div/label/span</value>
      <webElementGuid>e42e9f19-30d8-4b4a-a482-78ca062fd025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[1]/following::span[1]</value>
      <webElementGuid>da3a4df9-4a16-4dce-b3da-69057b8af71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanwil'])[2]/following::span[13]</value>
      <webElementGuid>ce5218f8-52db-4b08-a350-1821c3647ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[2]/preceding::span[1]</value>
      <webElementGuid>b2e3ae18-b679-4ad4-aaee-587cfe30a081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBMIT'])[1]/preceding::span[137]</value>
      <webElementGuid>86c79680-eb9c-4c16-a710-b134d86c281d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/table/thead/tr/th/div/label/span</value>
      <webElementGuid>6e624fb5-b79f-4479-854f-51c8869283d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
