<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KCU_body</name>
   <tag></tag>
   <elementGuidId>7382f644-31e2-4d52-be84-bd542dcb30c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-kanwil-kcu']/tbody/tr[${kanwil}]/td/div/label/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;table-kanwil-kcu&quot;)/tbody[1]/tr[${kanwil}]/td[@class=&quot;text-center&quot;]/div[@class=&quot;checkbox-wrapper&quot;]/label[1]/span[@class=&quot;cbx&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ff4ac1f8-9ba2-4895-a714-df88edbef3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbx</value>
      <webElementGuid>946c8ed0-21c0-4d1e-b129-9e72fd9c4d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-kanwil-kcu&quot;)/tbody[1]/tr[${kanwil}]/td[@class=&quot;text-center&quot;]/div[@class=&quot;checkbox-wrapper&quot;]/label[1]/span[@class=&quot;cbx&quot;]</value>
      <webElementGuid>2dbf8151-629f-4ad0-b5cc-797e28bc275d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-kanwil-kcu']/tbody/tr[2]/td/div/label/span</value>
      <webElementGuid>183720f4-9326-42c3-a751-e5040711c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[2]/following::span[2]</value>
      <webElementGuid>160909d9-4a21-4023-b846-7625be8fda1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[1]/following::span[3]</value>
      <webElementGuid>920f3c18-0fea-40c3-9858-5539cd9fc821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBMIT'])[1]/preceding::span[135]</value>
      <webElementGuid>5907bfa4-99a3-4de7-8eac-f58fc9ddf20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/preceding::span[135]</value>
      <webElementGuid>22768d4e-7ec6-447e-8d48-b00a1897a578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/table/tbody/tr[2]/td/div/label/span</value>
      <webElementGuid>f50c1235-a872-4ca5-a521-9e59ec5da079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
