<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kanwil_body</name>
   <tag></tag>
   <elementGuidId>05e4a704-69e9-4caa-84f9-f9c31f9aa8bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-kanwil']/tbody/tr[${kanwil}]/td/div/label/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='table-kanwil']/tbody/tr[${kanwil}]/td/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>219fdf26-fb40-419c-981a-3d90d2b8cec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbx</value>
      <webElementGuid>44b20a1a-cb24-4d1c-9041-ae73725d9b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='table-kanwil']/tbody/tr[${kanwil}]/td/div/label/span</value>
      <webElementGuid>898c4155-bab1-4191-b214-317b85d06f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-kanwil']/tbody/tr[2]/td/div/label/span</value>
      <webElementGuid>1c630dc4-7132-462e-8979-27d1310f6ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanwil'])[2]/following::span[2]</value>
      <webElementGuid>0eb2f707-c93d-4842-8c57-c6ea496ffd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanwil'])[1]/following::span[3]</value>
      <webElementGuid>92b43460-3ee2-45af-9c7d-7356083e0b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[1]/preceding::span[11]</value>
      <webElementGuid>9a7a1df0-24f7-431b-a175-4db87c7f4962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[2]/preceding::span[12]</value>
      <webElementGuid>26e99a18-c4e8-4470-9985-4b25e21bfcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/label/span</value>
      <webElementGuid>5de448ec-0791-4eec-a1c6-04340c33c634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
