<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kanwil_cbx</name>
   <tag></tag>
   <elementGuidId>1f2d2aa2-910d-47e3-ab33-6ac094e0eade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cbx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-kanwil']/thead/tr/th/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adf4e330-c2fd-4abc-a54e-a35ac88ea9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbx</value>
      <webElementGuid>4a38a05b-d2ac-4755-8019-26ff9be8f353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-kanwil&quot;)/thead[1]/tr[1]/th[@class=&quot;text-center&quot;]/div[@class=&quot;checkbox-wrapper&quot;]/label[1]/span[@class=&quot;cbx&quot;]</value>
      <webElementGuid>69c242c0-cbb6-4f25-930a-0e9bf4814d75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-kanwil']/thead/tr/th/div/label/span</value>
      <webElementGuid>30aa90cb-760e-4a1d-a4c8-c332fe65b2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanwil'])[1]/following::span[1]</value>
      <webElementGuid>c2ef746e-d8e9-4879-9a6d-617c67efe414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[1]</value>
      <webElementGuid>286cefe3-40b3-4d47-9490-02f1fef92570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kanwil'])[2]/preceding::span[1]</value>
      <webElementGuid>f68c8246-09e5-48c1-8972-6a81fe5a875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KCU'])[1]/preceding::span[13]</value>
      <webElementGuid>25263083-2fc4-4b57-8699-9ac90f8afb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>1d5b3e92-25fa-4c28-b10f-66d804533cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
