<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click-Event - Kanwil - KCU</name>
   <tag></tag>
   <elementGuidId>d0e336ff-2d78-447a-9c24-8bf0aedf2456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_mapping_kanwil_kcu > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='event_mapping_kanwil_kcu']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f9a304a-5b23-48c1-9822-4d7c0b9f20df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master/event_mapping_kanwil_kcu</value>
      <webElementGuid>a4570ad0-3e5e-4bd6-a334-f4925c6e913f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event - Kanwil - KCU</value>
      <webElementGuid>d22d2813-b0fb-4cc5-b713-e916066b6c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event_mapping_kanwil_kcu&quot;)/a[1]</value>
      <webElementGuid>e66b00ae-e2bc-4170-96ee-136a4fea0867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='event_mapping_kanwil_kcu']/a</value>
      <webElementGuid>ca74a740-291c-4a1c-98d8-cee5fe03d188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Event - Kanwil - KCU')]</value>
      <webElementGuid>310b7a47-64ac-4d45-afbd-cc7c615cc221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event - Dealer'])[1]/following::a[1]</value>
      <webElementGuid>0509c3fd-cdc8-42c3-a291-129635c178fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Event'])[1]/following::a[2]</value>
      <webElementGuid>ac830046-5c31-4381-9c21-522110d944fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='House Keeping'])[1]/preceding::a[1]</value>
      <webElementGuid>8b1e1bf2-5383-461e-a84b-22afb02db581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::a[2]</value>
      <webElementGuid>e45f1c25-c1b3-4df2-9f9b-11f60f0991e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Event - Kanwil - KCU']/parent::*</value>
      <webElementGuid>7bd85aea-a8fb-4d71-a30d-ffedbd9fc02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/master/event_mapping_kanwil_kcu')]</value>
      <webElementGuid>88eddd26-2b5d-49e5-afde-7ee1d81b4ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[3]/a</value>
      <webElementGuid>4ca2cf38-bb9a-45c3-b654-7157c9e02143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/master/event_mapping_kanwil_kcu' and (text() = 'Event - Kanwil - KCU' or . = 'Event - Kanwil - KCU')]</value>
      <webElementGuid>c6d36c62-bb48-47bd-9944-a2bbfcae9804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
