<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Master Event</name>
   <tag></tag>
   <elementGuidId>2e452dd1-5a62-4e29-af7c-5ef1a9b8c004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='event']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f33ca177-8b56-4ab3-8816-83362cb1ab74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master/event</value>
      <webElementGuid>8900be1a-c70d-4eed-b77a-d44b6d72a73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Event</value>
      <webElementGuid>7d3bb694-eca9-41e6-abaa-a6bd98e29075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event&quot;)/a[1]</value>
      <webElementGuid>1ce4adfe-d952-4213-b021-684366f8c54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='event']/a</value>
      <webElementGuid>bb082e7d-64c0-4d0a-af20-2ea7f1403ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Event')]</value>
      <webElementGuid>9d6ba09b-3d5c-4c4e-9cd5-81821046a8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[1]</value>
      <webElementGuid>b6113cd2-67fd-4ef4-b5d5-d20df5a2154b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapping Notifikasi'])[1]/following::a[2]</value>
      <webElementGuid>73de358d-da82-419b-98cc-7b8e04fc7970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event - Dealer'])[1]/preceding::a[1]</value>
      <webElementGuid>43d089ee-cff5-487e-8e84-9b49ecff0997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event - Kanwil - KCU'])[1]/preceding::a[2]</value>
      <webElementGuid>791c9c66-2e5f-438d-b06c-6ec532d17eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Event']/parent::*</value>
      <webElementGuid>6d6598ce-4199-4b3f-a24e-16afb6f0302c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/master/event')]</value>
      <webElementGuid>26b1cea0-a56f-4e04-a74d-2ff460a5cda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>49ded6a1-94c1-4c83-84a9-d99d15fc02d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/master/event' and (text() = 'Master Event' or . = 'Master Event')]</value>
      <webElementGuid>3ab9686a-130f-45d6-8eb2-87782341caf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
