<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sidebar-dashboard</name>
   <tag></tag>
   <elementGuidId>ce0c1b3a-5008-47a8-bb73-be1a5da5f235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='container']/header/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>747e365a-8ef9-444e-abf5-3f331b0a4aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars</value>
      <webElementGuid>04f347ac-9253-4fb1-b681-9ebc07f177b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/header[@class=&quot;header white-bg&quot;]/div[@class=&quot;sidebar-toggle-box&quot;]/i[@class=&quot;fa fa-bars&quot;]</value>
      <webElementGuid>b67fb500-437f-4cbc-a5c1-f84183935ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='container']/header/div/i</value>
      <webElementGuid>b970a5e3-4c80-4f7f-ab8c-133cbf24e85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>0994a1d6-4a0e-40ef-bbdc-ac4cbc85dc64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
