<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Master Data</name>
   <tag></tag>
   <elementGuidId>6f7327c8-4846-4a53-ab87-8b931deadc93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master > span.dcjq-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='master']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ab0e34f-0ec7-461c-8153-d14789a349c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcjq-icon</value>
      <webElementGuid>679bf2ab-9f5a-4f2d-8a7d-365b408c0018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master&quot;)/span[@class=&quot;dcjq-icon&quot;]</value>
      <webElementGuid>fbff7780-c156-432c-827c-8c46925c0165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='master']/span[2]</value>
      <webElementGuid>375163e2-d28d-4654-9ecf-8a37258a9830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span[2]</value>
      <webElementGuid>35d9b271-0d9c-41cf-aef7-72e6ecf827de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
