<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>80d38806-6f0b-4ed7-aa42-f5585b071ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.ml-auto.btn-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/div[2]/div/section/div/div/div/section/div[2]/div[2]/section/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f2665cb-da48-4e0f-ab28-c6612ac097e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://192.168.29.74/master/event_mapping_dealer</value>
      <webElementGuid>807e2de6-b47d-4898-88cc-229252bf4a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default ml-auto btn-lg</value>
      <webElementGuid>1c9a7eaa-c925-4d9b-91e6-fd9246c868e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>c7e1135c-1457-4b2f-afcb-e5e2b2d35a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/section[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/section[@class=&quot;card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/section[@class=&quot;panel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;button-submit&quot;]/div[1]/a[@class=&quot;btn btn-default ml-auto btn-lg&quot;]</value>
      <webElementGuid>54ada939-b8a5-48a3-ac6d-694057cd24a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Page_Event Dealer/edit_data/iframe_Logout_main-iframe</value>
      <webElementGuid>b692813a-38bb-42b0-a38b-d2953304aa86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/div[2]/div/section/div/div/div/section/div[2]/div[2]/section/div[2]/div/div/a</value>
      <webElementGuid>72d1fa5c-8633-4b48-b0a6-689e4b0bd9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>30f74bc2-4351-4992-86b3-f4c48abd464e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 2,189 entries'])[1]/following::a[10]</value>
      <webElementGuid>c6d20733-f7cf-4c7c-b44e-aaa1dc751df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. S. Wiryopranoto No. 49-51 (d/h Sawah Besar)'])[1]/following::a[10]</value>
      <webElementGuid>07de7666-b91d-42f1-8a08-732e83512cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::a[1]</value>
      <webElementGuid>5ae48ffc-6421-4f14-ab6a-2191818bc281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>3a698b7f-ef4a-4105-842f-ab86e74a306a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://192.168.29.74/master/event_mapping_dealer']</value>
      <webElementGuid>f5be8cc7-f666-4390-a3bf-45163512557f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>d3a67097-99d3-4aaf-8ce0-5c405d0d84ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://192.168.29.74/master/event_mapping_dealer' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>221d6887-c911-4ce2-8f58-8d23257d178c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
