<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>59fc5ff2-67b2-477b-bb2c-7c5d8998a323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-dealer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-dealer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb494085-b75f-498c-a2ae-58a1e9d4b3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e28f2444-9274-4463-aede-3086ec46fc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-dealer</value>
      <webElementGuid>753b5d02-f2a5-4773-9f33-33e847df58d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitDealer()</value>
      <webElementGuid>f573bc2e-a4e5-4185-96d7-702f27918a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ml-auto btn-lg</value>
      <webElementGuid>8cacf00b-3858-4bb0-85fe-3be18363be41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>2532943e-bf06-4940-b6e9-e75e6a289d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-dealer&quot;)</value>
      <webElementGuid>4a9d5755-2cd3-4038-8fc3-243b0dec42ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Page_Event Dealer/edit_data/iframe_Logout_main-iframe</value>
      <webElementGuid>b11b5c90-d876-4a02-b558-d54e7186bf8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-dealer']</value>
      <webElementGuid>d67ce12d-073c-4e78-bc5d-f40b70532603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/div[2]/div/section/div/div/div/section/div[2]/div[2]/section/div[2]/div/div/button</value>
      <webElementGuid>ca4d5bbc-e515-4a96-9af4-7eef3d422c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>72dbcac6-d714-404b-9182-dc1d73d2ded7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 2,189 entries'])[1]/following::button[1]</value>
      <webElementGuid>7b8c6418-2044-469a-a199-21b954ebcc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'submit-dealer', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>2aa23849-7405-4eac-9cdd-eda12760886d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>b893ef20-0287-4f59-99dd-6531f5d50f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9f955d3f-0cc1-4779-bc60-135344a7add8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submit-dealer' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>7e317ebe-ffd3-42c7-94e5-21d5b0368986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
