<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout_main-iframe</name>
   <tag></tag>
   <elementGuidId>0bd63554-7a36-43ae-a08c-dc2a0e5c188b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='main-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a5828bd8-2acd-41d1-a811-0c5b19511bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-iframe</value>
      <webElementGuid>7323dafc-3a2a-4b4f-a97f-272c4ffe69ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/master/event_dealer/list</value>
      <webElementGuid>0dd2b6dc-4e6e-435c-851d-3a8a3c9fe652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>45cd12d2-b5f6-494e-b99f-717a71f6270b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d0113c8e-d813-4773-83f5-4f76ae1f2c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1000px</value>
      <webElementGuid>499b35cc-7160-4e79-a6b6-4760c9119ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-iframe&quot;)</value>
      <webElementGuid>dba22cb4-f971-45ee-88e6-1a782c935098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='main-iframe']</value>
      <webElementGuid>a268a8a8-7603-4367-b57d-09c9966096aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div/iframe</value>
      <webElementGuid>3c5afd19-4d51-426b-95d1-1a9ae02f3ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>be22f615-29a3-4716-898e-eb3b0ed28361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'main-iframe' and @src = '/master/event_dealer/list']</value>
      <webElementGuid>731a8c9d-545b-411c-bfda-8b60c7198fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
