<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Dealer_myInputTextField</name>
   <tag></tag>
   <elementGuidId>b840c639-d0a7-4ac6-8de3-a8348e938800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myInputTextField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myInputTextField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9654b195-e602-49bb-b20d-234cd5baafd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29e232d2-0383-4c07-8c10-a0f2fa9bb857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myInputTextField</value>
      <webElementGuid>9f6ade97-f1e6-46e0-9065-390e07ac6b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Dealer</value>
      <webElementGuid>0ad7d7e7-12b9-4f24-ba26-3049a3dd7d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myInputTextField&quot;)</value>
      <webElementGuid>09cbe052-3979-4c7b-bfe0-dae56d12b8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Page_Event Dealer/iframe_Logout_main-iframe</value>
      <webElementGuid>51e13fde-1d88-412e-82c7-4f26911f0c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myInputTextField']</value>
      <webElementGuid>d07a25e4-7b6d-428a-a633-c8a2dacddb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/div[2]/div/section/div/div/div/section/div[2]/div[2]/div/div/input</value>
      <webElementGuid>a6da9841-5207-4e9b-a3e1-45eb8ae750c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>dae9cad2-9b68-41b9-9c03-61fc4b1fb655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'myInputTextField' and @placeholder = 'Cari Dealer']</value>
      <webElementGuid>2b94c75d-2238-4fae-b4bd-deb37144192c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
