<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bulan</name>
   <tag></tag>
   <elementGuidId>703e9f01-265b-4620-946a-e1eae2ed51cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Mar' or . = 'Mar')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Mar' or . = 'Mar') and @ref_element = 'Object Repository/CMS/Page_Master Event/iframe_Buat Event Baru_popupiframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>712f2686-48f9-413c-8cdd-b1c41788c7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>38171ce7-be04-4e90-93a4-59846d8da7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mar</value>
      <webElementGuid>a07b068a-d0a9-44fb-96ba-d9266037dc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;month&quot;]</value>
      <webElementGuid>590c21fe-9992-4b5a-927c-81f7d893678b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Page_Master Event/iframe_Buat Event Baru_popupiframe</value>
      <webElementGuid>0b996ea2-38cc-42db-b3b3-807dd5ae4557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mar' or . = 'Mar')]</value>
      <webElementGuid>10806d15-f8aa-4452-bb92-c30ee8820ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
