<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Master Event_main-iframe</name>
   <tag></tag>
   <elementGuidId>ce185ae8-07aa-487a-bff6-55f77d73d0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='main-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e9c7961f-b352-4d2c-91e2-c2986fde720d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-iframe</value>
      <webElementGuid>843de2e9-cb6a-472f-a108-7fdee8268af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/master/event/list</value>
      <webElementGuid>a2bc9e7d-f265-4f12-bd69-4a1923ed7a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90e98bff-ec63-45dd-98f4-6977868828c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>29e396d8-286a-444c-932a-15ff521c432b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>750px;</value>
      <webElementGuid>b2ae29b4-566a-4535-a7d7-5e301cafd8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-iframe&quot;)</value>
      <webElementGuid>8c7dd9e2-3b54-4cf9-8e4c-2112d68c879c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='main-iframe']</value>
      <webElementGuid>64eb254d-faf8-4447-920f-4a748c82aa9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div[2]/div/section/div/iframe</value>
      <webElementGuid>cd65287f-5214-4cfd-9dcb-167fcc1c1756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>22b3afc4-53db-4fcf-aabe-db9c976ba153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'main-iframe' and @src = '/master/event/list']</value>
      <webElementGuid>d93c05a4-70d5-449c-89af-798b98eae4c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
