<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dari Tanggal</name>
   <tag></tag>
   <elementGuidId>4ad28412-ff6e-47eb-92bd-1a946a601e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#periode_from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='periode_from']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f2c8f1f-b3ec-4e9e-a42f-ce292e2087b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebc53133-0343-4536-bcfd-a99bc192b4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>periode_from</value>
      <webElementGuid>abaa55d7-823d-4e15-8812-815c8b6cb001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>periode_from</value>
      <webElementGuid>2ee6dca2-b9bd-499a-8ddd-613d8b1f25aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bg-white</value>
      <webElementGuid>036d5f62-d138-41ea-bfa0-3f23d653f07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dari Tanggal</value>
      <webElementGuid>55abde42-44d9-4941-8bce-bd472ef483ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;periode_from&quot;)</value>
      <webElementGuid>4768d49a-b810-4a67-b0f3-9791cd3884af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Page_Master Event/iframe_Buat Event Baru_popupiframe</value>
      <webElementGuid>683bf7a8-a7ae-418d-869a-aa2fcbbc89db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='periode_from']</value>
      <webElementGuid>f1407bd5-849c-4d1d-9f23-dd0cfb17ea19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formCreate']/div[4]/div/div/input</value>
      <webElementGuid>41e82393-280a-4cf4-aa3c-b2bf3692778f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>f196f10d-f493-441c-aebd-a5d000367c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'periode_from' and @name = 'periode_from' and @placeholder = 'Dari Tanggal']</value>
      <webElementGuid>8693076a-713f-47fc-9e00-0dd632a47c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
