<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sorting_Status</name>
   <tag></tag>
   <elementGuidId>48ad0926-03bc-4e87-8948-70a66b5d6b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.text-center.sorting_desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dataTableBuilder']/thead/tr/th[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>4298f107-d54c-4b84-af2f-0854add21305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center sorting_desc</value>
      <webElementGuid>469e1578-e12a-4490-8af0-a3e426df49f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7b66514d-87bf-4185-8ca2-c0572677dc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dataTableBuilder</value>
      <webElementGuid>7331e6a1-6d2c-46d9-b085-1b311fa52d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>86ebd08f-d97d-4a82-b1e9-81a321883f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d5ddc861-36ef-42f6-8327-af5eb437444b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Status: activate to sort column ascending</value>
      <webElementGuid>b077c2a2-3e73-469b-9915-be01c2cb03a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>descending</value>
      <webElementGuid>6008a184-7f8e-4ee1-b5e9-16bb14be7b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>e583a205-94ab-4336-a835-e67cadc70c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTableBuilder&quot;)/thead[1]/tr[1]/th[@class=&quot;text-center sorting_desc&quot;]</value>
      <webElementGuid>8c304af5-1c31-4f59-8516-ce7287e6147a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CMS/Page_Master Sorting/iframe_Master Event_Sorting</value>
      <webElementGuid>cff3186e-72f0-4d1f-b612-30ac17950967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTableBuilder']/thead/tr/th[6]</value>
      <webElementGuid>8978110c-26a9-4673-a80c-a4b04ec40706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sampai Tanggal'])[1]/following::th[1]</value>
      <webElementGuid>57ffb161-c6cf-44cb-8eeb-fe684f7e3d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari Tanggal'])[1]/following::th[2]</value>
      <webElementGuid>fdee3464-d46c-49ca-9d07-2c54a07bd2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::th[1]</value>
      <webElementGuid>5e55e6c4-f07c-4f70-8767-b2d6d88b5d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVENT240007'])[1]/preceding::th[2]</value>
      <webElementGuid>427a2f85-3165-44b6-8f73-134f1a6271df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Status']/parent::*</value>
      <webElementGuid>9c84c314-496c-4285-8807-a2f93df510c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]</value>
      <webElementGuid>df6b0c6c-ab9a-4d11-919a-dbf21dafa3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Status' or . = 'Status')]</value>
      <webElementGuid>781cc9ae-debc-448d-96c5-635b30fdba08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
